### ISSUE TITLE
这个问题你找到原因了么？

### ISSUE THREAD

**Issue by rxliuli** [zhengxs2018/vitejs-monorepo-fullstack#1]
https://github.com/zhengxs2018/vitejs-monorepo-fullstack/blob/c5b1255b49f6c56137e23b34cb0e6207c0ede967/apps/web/vite.config.ts#L10-L11

**Comment by zhengxs2018** [comment]
还没

**Comment by rxliuli** [comment]
吾辈生产项目加了这个也不行 xd，还是再等等好了
